version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: ozmap_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: ozmap_api
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/ozmap

volumes:
  mongo_data:
